travis:
  secure:
    BINSTAR_TOKEN: FB66LEPqQ80+3ELgRkCjD7pYjfZuHTfpA/r7xeZ/EypQ475qrHaEIPTaynAhXNxsBhrt5wPqO9WT20jaAtmR7oaC5GCEfavq9xotVv1RECwcuY4e56VG6rnZ5xnWlNv8mpQFAyolDexQJ6JjG8ZwEVf1KQ3be8lMkPC/gghcLInnO7Au0uyZxt/Lq1OuBsdwhRSEH/ho0E0NiaPKOlK/8Nt+4BB60gGDPOlc3ki4n86HJ+84uZDBVsJxezay88gDmmThrttHxkjFAI0c0XrjeyVyevHuRN6OTQ8ndX0JxrGWDW63h0ZuTnJQwxLPWpbytNkdbEegZjIwEq1l1f4XLdTc4CWq27vCYD4jjwu2NsAL+kiOx6C25kXo/8dJaJcKUXEA6Xxg7MHL7mFH4tovlIjFUG7Unl4y+U4bxAd30nCpu2PhciKV0daQg+IVmKN8YkTXbPPW+kEbn38tsasoH+QQeYjY05iTbofjW1gSc4EncJ5OzkXO9cwaznUrGQ8C2JsAW4osLZ2kPe2iutUG5OEtlONeIg4Teg8m9CSgenMsqg9vFmAhxwzYXb/j2r/llp3EYajM+b4/KuwHga4eIZpUEtRlnkEmGSkEpjQSSXQFA6nUBlNY4Y4mH73ntIhFDBiLI3Ug5SOr1Sc/wy2V4UeSZBE37pMu8SBJfbSXAtQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
