travis:
  secure:
    BINSTAR_TOKEN: R4pizu99qOXU4G6rl7Z5HNefGEwpgyQ4slDQzXskZ5C9Z+E7Uk3lWhC8Tjk3XcN8epnqcW10eZ6i/Fo7B9MU5O8lGUYCOVuZpX20WdRBRhqvjSmQJArQAiALAYn4hHrLxupf+XdVuhEhBEZ0e10GwWw8HIc7KBmRmTO2KyjOLD+sOGQXmpI6YwrHPpn0elwvt9A0fq7puZD8KwEdz9AHD+fPcA3fqGrpE5s+OlH6T1546fZlCJMzSuji6y7Vm6ppS++LBAmieNVv8MHIir0HGJHq0BrJ/tE4MCTFdJE+OUWAxltDIzNmf7iPmfcjpSMZL83jhww4alyYHPA866RDJkKFziAsTgpT7mDa1unlrg9ZQjAYtG9/kJEURwifDMB8pqPfLnvznlIQMDssOpHWFpwo9tjY1RpPrwewvtjfWWUkIv/NgbcDEYoxr4e75IvweDHIg6ENiVihAddGZZA9Dkqz+cBL0PIo3d0C5ctJPL21C6ofe8MLBVjzd6Bu3XHZWs4eet64TWtPG5doBn6RCMiH8tVl29UZrt94J+kkExXMEdb6qHSFh0pjPIjwjC+HYwwyquZQ8UahwZzN9+6DOhRj4Wzro/bMFDUO+bRQK0bzav0zeY6nPhOhB/+eZdQ7TiSrQCqOrqPuZdq3oTeCwj6vdjXy2XpU5km/TXbXt40=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
